### ISSUE TITLE
Release versioned flagd-testbed image

### ISSUE THREAD

**Issue by skyerus** [open-feature/test-harness#17]
Currently, the test-harness builds, tags as `latest` and pushes the flagd-testbed image.
This practice has caused PR workflow processes to fail due to not absorbing test changes required by a later update of flagd.
While it is a good thing to be notified that the tests are failing against an upgraded flagd, having it apparent in unrelated PRs is cumbersome and confusing.

Imo, a better practice would be to version the flagd-testbed image (same version as the base flagd image) and introduce renovate config into the relevant repos to check for flagd-testbed image upgrades. This way any test failures against an upgraded flagd is only apparent in the renovate PR and it's immediately clear to see what's going wrong.

- [x] Version flagd-testbed image
- [x] [Implement renovate config that watches test-harness version in go-sdk](https://github.com/open-feature/go-sdk/issues/134)
- [x] [Implement renovate config that watches test-harness version in java-sdk](https://github.com/open-feature/java-sdk/issues/237)
- [x] [Implement renovate config that watches test-harness version in js-sdk](https://github.com/open-feature/js-sdk/issues/358)
